version: "3.4"

services:
  bookservice:
    image: userservice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  postgres:
    image: postgis/postgis:13-3.1-alpine
    container_name: userservice-postgres
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - "${DATABASE_HOSTNAME}:${DATABASE_PORT}:${DATABASE_PORT}"