version: '3.8'

services:
  book_service:
    image: book_service
    container_name: book_service
    build: ./book-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - ./book-service:/app/
    ports:
      - 8001:8001
    environment:
      - DATABASE_URI=postgresql://book_db_username:book_db_password@book_db/book_db_dev
      - USER_SERVICE_HOST_URL=http://user_service:8002/api/users/
    depends_on:
      - book_db

  book_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_book:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=book_db_username
      - POSTGRES_PASSWORD=book_db_password
      - POSTGRES_DB=book_db_dev
    ports:
          - "5435:5432"

  user_service:
    image: user_service
    container_name: user_service
    build: ./user-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8002
    volumes:
      - ./user-service:/app/
    ports:
      - 8002:8002
    environment:
      - DATABASE_URI=postgresql://user_db_username:user_db_password@user_db/user_db_dev
    depends_on:
      - user_db

  user_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_user:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_db_username
      - POSTGRES_PASSWORD=user_db_password
      - POSTGRES_DB=user_db_dev
    ports:
      - "5434:5432"

  nginx:
    image: nginx:1.21.6
    container_name: nginx_gateway
    depends_on:
      - book_service
      - user_service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  postgres_data_book:
  postgres_data_user: