# using Nginx base image
FROM nginx:stable-alpine
# delete nginx default .conf .file
RUN rm /etc/nginx/conf.d/default.conf
# add the .conf file we have created
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]


