"""
First test

Revision ID: 23caeb7af323
Revises: 
Create Date: 2022-02-21 15:50:43.077608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23caeb7af323'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Book')
    # ### end Alembic commands ###
