"""additional columns

Revision ID: 7203d9cefae4
Revises: 4f7e1e5cbca5
Create Date: 2022-05-03 16:26:09.202623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7203d9cefae4'
down_revision = '4f7e1e5cbca5'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('Books',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Books_id_seq"\'::regclass)'),
              autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Books_pkey')
    )
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Books_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Books_pkey')
    )
    # ### end Alembic commands ###
