"""First migration

Revision ID: 7da5f7515336
Revises: 1d79f2e82edb
Create Date: 2022-04-11 14:35:27.282745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da5f7515336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Reviews',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('content', sa.String(length=255), nullable=False),
        sa.Column('date', sa.DATE, nullable=False),
        # sa.Column('genre', sa.String(length=255), nullable=False),
        # sa.Column('year', sa.Integer, nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reviews')
