image: python:3.10
before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - test

# lint:
#   stage: test
#   script:
#     - pip install -r requirements.txt
#     - flake8

test:
  stage: test
  script:
    - cd test/;pytest -v
