version: '3.8'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
#    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001
    env_file:
      - ./.env
    environment:
      - DATABASE_HOSTNAME=user-db
    ports:
      - 8001:8001
    depends_on:
      - "user-db"
  user-db:
    image: postgres:13-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - "${DATABASE_HOSTNAME}:${DATABASE_PORT}:${DATABASE_PORT}"
