version: '3.8'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn app.api.server:app --reload --host 0.0.0.0 --port 8002
    env_file:
      - ./.env
    ports:
      - 8002:8000
    depends_on:
      - "db"
  db:
    image: postgres:13-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - 5434:5432
